language: python
dist: xenial
services:
- docker
matrix:
  include:
  # Django 2.0.x with Python 3.6 and 3.7
  - python: "3.6"
    env: DJANGO_REL="django>=2.0,<2.1"
  - python: "3.7"
    env: DJANGO_REL="django>=2.0,<2.1"
  # Django 2.1.x with Python 3.6 and 3.7
  # Also, run tests against Django 2.1.x, Python 3.6 and several database backends
  - python: "3.6"
    env: DJANGO_REL="django>=2.1,<2.2"
  - python: "3.6"
    env: DJANGO_REL="django>=2.1,<2.2" NITRATE_DB=mysql
  - python: "3.6"
    env: DJANGO_REL="django>=2.1,<2.2" NITRATE_DB=mariadb
  - python: "3.6"
    env: DJANGO_REL="django>=2.1,<2.2" NITRATE_DB=postgres
  - python: "3.7"
    env: DJANGO_REL="django>=2.1,<2.2"
  # Django 2.2.x with Python 3.6 and 3.7
  - python: "3.6"
    env: DJANGO_REL="django>=2.2,<2.3"
  - python: "3.7"
    env: DJANGO_REL="django>=2.2,<2.3"
before_install:
- docker pull mysql:5.7
- docker pull mariadb:10.2.21
- docker pull registry.fedoraproject.org/fedora:29
install: pip install coveralls
script:
- contrib/travis-ci/runtests.sh "$(python --version 2>&1)" "$DJANGO_REL" $NITRATE_DB
after_success:
- sudo chown travis:travis .coverage
- sed -i -e s@/code@"$(pwd)"@g .coverage
- coveralls
notifications:
  email:
    on_failure: change
    on_success: change
